CREATE DATABASE IF NOT EXISTS CharityStoreDB;
USE CharityStoreDB;
DROP TABLE IF EXISTS `ProductsInfo`;
CREATE TABLE `ProductsInfo` (`product_no` text,`product_name` text,`price` text,`inventory` text,`description` text,`image` text,`seller_no` text);
LOCK TABLES `ProductsInfo` WRITE;
INSERT INTO `ProductsInfo` VALUES ('1', 'Water Charity Level 1', 100.00, 5, 'For $100, be a supporting level member of the Water Charity','https://d11sa1anfvm2xk.cloudfront.net/media/downloads/logos/cw_vertical_black.jpg', '1');
INSERT INTO `ProductsInfo` VALUES ('2', 'Food Charity', 500.00, 3, 'For $500, be a Gold Tier member of the Food Charity. 3 slots available!','https://media.istockphoto.com/vectors/food-donation-and-charity-vector-id1224414210','2');
INSERT INTO `ProductsInfo` VALUES ('3', 'School Supply Charity', 50.00, 20,'For $50, help a class of 20 in a NYC public school buy textbooks!','https://catholiccharities.org/wp-content/uploads/2020/07/School-Supplies-Teacher-Appreciation-Invitation-2-300x300.png', '3');
INSERT INTO `ProductsInfo` VALUES ('4', 'Water Charity Friend Level', 50.00, 15, 'For $50, be a friend of the Water Charity','https://d11sa1anfvm2xk.cloudfront.net/media/downloads/logos/cw_vertical_black.jpg', '1');
UNLOCK TABLES;